# These are supported funding model platforms

custom: ['https://www.paypal.com/donate/?token=ryrdIoIhpGFl8I8IXKKL9XXElDWns5-sLEMT_HoTO23btCWi_2Zzh9bmWHT2HQJuudqAd0&fromUL=true&country.x=GB&locale.x=en_GB'] 
